### ISSUE TITLE
Questions for multiple GPUs training

### ISSUE THREAD

**Issue by K-Yii** [a-r-r-o-w/cogvideox-factory#113]
### System Info / 系統信息

I use the official script ./train_image_to_video_lora.sh for multi-card training, and uncompiled_2.yaml for accelerate_config. I found that the training time of 4 cards and 8 cards is similar under the same steps and batch conditions. I expect to use 8 cards to save about half the time.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

#### uncompiled_2.yaml
ompute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: 0,1,2,3,4,5,6,7
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

#### train_settings
MAX_TRAIN_STEPS=("3000")
ACCELERATE_CONFIG_FILE="accelerate_configs/uncompiled_2.yaml"
train_batch_size=1

### Expected behavior / 期待表现

I expected that the training time for multi-GPU training would be much shorter under the same settings and the same effect.

**Comment by lgs00** [comment]
I also had problems with inefficient training. I used the deepspeed training method, 

**train_batch_size=2, gradient_accumulation_steps=4,** 

and trained **cogvideo-5b-t2v-sft**. 

<img width="677" alt="image" src="https://github.com/user-attachments/assets/f84f9319-8700-4d37-9953-54a0a0f63af0">

Graphics DutyCycle  is always less than 100%, is this normal？

<img width="267" alt="image" src="https://github.com/user-attachments/assets/6e0c2454-804b-460f-b7c8-e6fbee4b9af3">

**Comment by Vincentyua** [comment]
I would like to ask how you perform multi-GPU training. When I use train_text_to_video_sft.sh for multi-GPU training, once the number of GPUs exceeds 1, it directly freezes and does not load the model or start training. I have made almost no modifications, only changing the dataset in the script. I hope to learn from your experience.

**Comment by K-Yii** [comment]
> I would like to ask how you perform multi-GPU training. When I use train_text_to_video_sft.sh for multi-GPU training, once the number of GPUs exceeds 1, it directly freezes and does not load the model or start training. I have made almost no modifications, only changing the dataset in the script. I hope to learn from your experience.

I use the train_text_to_video_sft.sh script with the example settings like uncompiled_2.yaml, and can train on multiple GPUs normally, but there is still a problem that the training speed is not accelerated. Maybe you can log at each stage of training to see where it gets stuck.

**Comment by a-r-r-o-w** [comment]
I've explained [here](https://github.com/a-r-r-o-w/cogvideox-factory/issues/111#issuecomment-2516222917) on what needs to be done to maintain a fair comparison when increasing batch size. TLDR; if you increase batch_size by 2x, you need to reduce the number of training steps by 2x. This type of data loading and training is common across most diffusers training scripts because it tries to maintain the notion of "effective number of samples seen by the model during training".

**Comment by K-Yii** [comment]
> I've explained [here](https://github.com/a-r-r-o-w/cogvideox-factory/issues/111#issuecomment-2516222917) on what needs to be done to maintain a fair comparison when increasing batch size. TLDR; if you increase batch_size by 2x, you need to reduce the number of training steps by 2x. This type of data loading and training is common across most diffusers training scripts because it tries to maintain the notion of "effective number of samples seen by the model during training".

I'm sorry I just saw this issue, I understand you mean that the number of samples seen for my 8-gpus training is already twice that of the 4-gpus training. I should reduce the step by half to compare the training cost, right?

**Comment by a-r-r-o-w** [comment]
Yes that's correct. If you keep the product of `num_gpus`, `batch_size` and `num_training_steps` constant, you will see that higher batch size will lead to faster training on higher-end GPUs

**Comment by Vincentyua** [comment]
> > I would like to ask how you perform multi-GPU training. When I use train_text_to_video_sft.sh for multi-GPU training, once the number of GPUs exceeds 1, it directly freezes and does not load the model or start training. I have made almost no modifications, only changing the dataset in the script. I hope to learn from your experience.
> 
> I use the train_text_to_video_sft.sh script with the example settings like uncompiled_2.yaml, and can train on multiple GPUs normally, but there is still a problem that the training speed is not accelerated. Maybe you can log at each stage of training to see where it gets stuck.

I also used uncompiled_2.yaml, with the following modifications:

`compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: 0,1,2,3,4,5,6,7
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false`

 However, it still gets stuck, and the GPU memory is not being used. I'm very curious about where the problem lies.
