### ISSUE TITLE
When using train_text_to_video_sft.sh for multi-card training, once the number of cards exceeds 1, it directly gets stuck and does not load the model or train. I have basically made no changes, only replaced the dataset in the sh file. How can I perform multi-card training?

### ISSUE THREAD

**Issue by Vincentyua** [a-r-r-o-w/cogvideox-factory#115]
### System Info / 系統信息

cuda：12.5.0
python：3.10
GPU:H20

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. down Disney-VideoGeneration-Dataset
2. modify train_text_to_video_sft.sh dataset name and dir, and gpu ids
3. run train_text_to_video_sft.sh
4. it doesn’t to load model and training，it will blocked，and the gpu memory is used 0 G

### Expected behavior / 期待表现

Hope that multiple GPUs can successfully train to improve training speed.

**Comment by a-r-r-o-w** [comment]
For multi-GPU training, you need to ensure that accelerate config is appropriately created.

You can use the interactive interface for creating a config as: `accelerate config --config-file myconfig.yaml`

**Comment by Vincentyua** [comment]
yes,I have obtained the configuration based on the interaction, but it cannot run. The command execution gets stuck, and there is no increase in video memory.
![image](https://github.com/user-attachments/assets/805f152c-7127-42fe-b6fb-d98af539956f)
it seem like model weight not load to GPU memory，this is very confused

**Comment by Vincentyua** [comment]
I found my problem, it was because I set localhost in the script during single GPU training, which caused a connection timeout. Thank you very much for your explanation.
