### ISSUE TITLE
the keywords are not expected by CogVideoXPipeline

### ISSUE THREAD

**Issue by lgs00** [a-r-r-o-w/cogvideox-factory#118]
After sft the cogvideo transforme. When infer, why does the keywords are not expected by CogVideoXPipeline? What should I do with the model after sft.

> run train_text_to_video_sft.sh with 5b-t2v.

`    transformer_model=CogVideoXTransformer3DModel.from_pretrained(transformer_path,torch_dtype=torch.float16)
`    
`    pipe = CogVideoXPipeline.from_pretrained(
`        
`    base_model,
`        
`    transfromer=transformer_model,
`        
`    torch_dtype=torch.float16
`  
`  )`

`The config attributes {'ofs_embed_dim': None, 'patch_bias': True, 'patch_size_t': None} were passed to CogVideoXTransformer3DModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Keyword arguments {'transfromer': CogVideoXTransformer3DModel(
  (patch_embed): CogVideoXPatchEmbed(
    (proj): Conv2d(16, 3072, kernel_size=(2, 2), stride=(2, 2))
    (text_proj): Linear(in_features=4096, out_features=3072, bias=True)
  )
......
  (proj_out): Linear(in_features=3072, out_features=64, bias=True)
)} are not expected by CogVideoXPipeline and will be ignored.`

**Comment by paperheart** [comment]
@lgs00 你好我同样遇到了这个问题，请问怎么解决？感谢🙏！

**Comment by paperheart** [comment]
https://huggingface.co/THUDM/CogVideoX1.5-5B-I2V/discussions/3

I solved it via the solution.
