### ISSUE TITLE
What resolution size is recommended for MP4 videos? What should the bitrate be set to? Should the video use H.264 or H.265 encoding?

### ISSUE THREAD

**Issue by Erwin11** [a-r-r-o-w/cogvideox-factory#22]
About Dataset Preparation, 
What resolution size is recommended for MP4 videos? What should the bitrate be set to? Should the video use H.264 or H.265 encoding?
example： 1280X720, 5mbps below. recommended  H.264 encoder.

Is any suggestion here?

**Comment by a-r-r-o-w** [comment]
cc @zRzRzRzRzRzRzR

**Comment by Erwin11** [comment]
https://github.com/a-r-r-o-w/cogvideox-factory/blob/main/assets/dataset.md
