### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement diffusers>=0.30.4

### ISSUE THREAD

**Issue by yafangwang9** [a-r-r-o-w/cogvideox-factory#30]
### System Info / 系統信息

python 3.10.11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在pip install -r requirements.txt这一步

### Expected behavior / 期待表现

requirements.txt中写了diffusers>=0.30.4，但实际上只需是0.30.3？
https://github.com/huggingface/diffusers/releases

**Comment by yafangwang9** [comment]
还有panda==2.2.3

**Comment by a-r-r-o-w** [comment]
Fixed in #27
