### ISSUE TITLE
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

### ISSUE THREAD

**Issue by yafangwang9** [a-r-r-o-w/cogvideox-factory#36]
### System Info / 系統信息

4090单卡，在ubuntu下，环境严格按照requirements.txt环境进行安装

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我使用的数据集是迪士尼数据集，https://huggingface.co/datasets/Wild-Heart/Disney-VideoGeneration-Dataset
用的模型是CogVideoX-5b这个模型型号，https://huggingface.co/THUDM/CogVideoX-5b

### Expected behavior / 期待表现

在运行./train_text_to_video_lora.sh出现了以下问题
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'training/cogvideox_text_to_video_lora.py', '--pretrained_model_name_or_path', '/root/cogvideox-factory/THUDM/CogVideoX-5b', '--data_root', '/root/cogvideox-factory/my/datasets', '--caption_column', '/root/cogvideox-factory/my/datasets/prompt.txt', '--video_column', '/root/cogvideox-factory/my/datasets/videos.txt', '--id_token', 'BW_STYLE', '--height_buckets', '480', '--width_buckets', '720', '--frame_buckets', '49', '--dataloader_num_workers', '8', '--pin_memory', '--validation_prompt', "BW_STYLE A black and white animated scene unfolds with an anthropomorphic goat surrounded by musical notes and symbols, suggesting a playful environment. Mickey Mouse appears, leaning forward in curiosity as the goat remains still. The goat then engages with Mickey, who bends down to converse or react. The dynamics shift as Mickey grabs the goat, potentially in surprise or playfulness, amidst a minimalistic background. The scene captures the evolving relationship between the two characters in a whimsical, animated setting, emphasizing their interactions and emotions:::BW_STYLE A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical performance", '--validation_prompt_separator', ':::', '--num_validation_videos', '1', '--validation_epochs', '10', '--seed', '42', '--rank', '128', '--lora_alpha', '128', '--mixed_precision', 'bf16', '--output_dir', '/root/cogvideox-factory/models/cogvideox-lora__optimizer_adam__steps_3000__lr-schedule_cosine_with_restarts__learning-rate_1e-3/', '--max_num_frames', '49', '--train_batch_size', '1', '--max_train_steps', '3000', '--checkpointing_steps', '1000', '--gradient_accumulation_steps', '1', '--gradient_checkpointing', '--learning_rate', '1e-3', '--lr_scheduler', 'cosine_with_restarts', '--lr_warmup_steps', '400', '--lr_num_cycles', '1', '--enable_slicing', '--enable_tiling', '--optimizer', 'adam', '--beta1', '0.9', '--beta2', '0.95', '--weight_decay', '0.001', '--max_grad_norm', '1.0', '--allow_tf32', '--report_to', 'wandb', '--nccl_timeout', '1800']' returned non-zero exit status 1.

希望能得到帮助！感谢

**Comment by yafangwang9** [comment]
> I think the failure stack trace is missing and this is only part of it. Could you paste the complete stack trace?

thank you very much！！

**Comment by a-r-r-o-w** [comment]
Oh sorry, the diffusers version in requirements.txt is incorrect again. You need to install it from the main branch for this to work as we haven't made a diffusers release with CogVideoX lora loading support yet. Please do:

`pip install git+https://github.com/huggingface/diffusers`

**Comment by yafangwang9** [comment]
> Oh sorry, the diffusers version in requirements.txt is incorrect again. You need to install it from the main branch for this to work as we haven't made a diffusers release with CogVideoX lora loading support yet. Please do:
> 
> `pip install git+https://github.com/huggingface/diffusers`

Thank you very much！The issue with the diffusers version has been resolved, but now I'm encountering `torch.OutOfMemoryError: CUDA out of memory`. I'm using a single 4090 GPU. Is there something wrong with the step I took?


Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'training/cogvideox_text_to_video_lora.py', '--pretrained_model_name_or_path', '/root/cogvideox-factory/THUDM/CogVideoX-5b', '--data_root', '/root/cogvideox-factory/my/datasets', '--caption_column', '/root/cogvideox-factory/my/datasets/prompt.txt', '--video_column', '/root/cogvideox-factory/my/datasets/videos.txt', '--id_token', 'BW_STYLE', '--height_buckets', '480', '--width_buckets', '720', '--frame_buckets', '49', '--dataloader_num_workers', '8', '--pin_memory', '--validation_prompt', "BW_STYLE A black and white animated scene unfolds with an anthropomorphic goat surrounded by musical notes and symbols, suggesting a playful environment. Mickey Mouse appears, leaning forward in curiosity as the goat remains still. The goat then engages with Mickey, who bends down to converse or react. The dynamics shift as Mickey grabs the goat, potentially in surprise or playfulness, amidst a minimalistic background. The scene captures the evolving relationship between the two characters in a whimsical, animated setting, emphasizing their interactions and emotions:::BW_STYLE A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical performance", '--validation_prompt_separator', ':::', '--num_validation_videos', '1', '--validation_epochs', '10', '--seed', '42', '--rank', '128', '--lora_alpha', '128', '--mixed_precision', 'bf16', '--output_dir', '/root/cogvideox-factory/models/cogvideox-lora__optimizer_adamw,__steps_3000__lr-schedule_cosine_with_restarts__learning-rate_1e-3/', '--max_num_frames', '49', '--train_batch_size', '1', '--max_train_steps', '3000', '--checkpointing_steps', '1000', '--gradient_accumulation_steps', '1', '--gradient_checkpointing', '--learning_rate', '1e-3', '--lr_scheduler', 'cosine_with_restarts', '--lr_warmup_steps', '400', '--lr_num_cycles', '1', '--enable_slicing', '--enable_tiling', '--optimizer', 'adamw,', '--beta1', '0.9', '--beta2', '0.95', '--weight_decay', '0.001', '--max_grad_norm', '1.0', '--allow_tf32', '--report_to', 'wandb', '--nccl_timeout', '1800']' returned non-zero exit status 2.
-------------------- Finished executing script --------------------

Running command: accelerate launch --config_file accelerate_configs/uncompiled_1.yaml --gpu_ids 0 training/cogvideox_text_to_video_lora.py           --pretrained_model_name_or_path /root/cogvideox-factory/THUDM/CogVideoX-5b           --data_root /root/cogvideox-factory/my/datasets           --caption_column /root/cogvideox-factory/my/datasets/prompt.txt           --video_column /root/cogvideox-factory/my/datasets/videos.txt           --id_token BW_STYLE           --height_buckets 480           --width_buckets 720           --frame_buckets 49           --dataloader_num_workers 8           --pin_memory           --validation_prompt "BW_STYLE A black and white animated scene unfolds with an anthropomorphic goat surrounded by musical notes and symbols, suggesting a playful environment. Mickey Mouse appears, leaning forward in curiosity as the goat remains still. The goat then engages with Mickey, who bends down to converse or react. The dynamics shift as Mickey grabs the goat, potentially in surprise or playfulness, amidst a minimalistic background. The scene captures the evolving relationship between the two characters in a whimsical, animated setting, emphasizing their interactions and emotions:::BW_STYLE A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical performance"           --validation_prompt_separator :::           --num_validation_videos 1           --validation_epochs 10           --seed 42           --rank 128           --lora_alpha 128           --mixed_precision bf16           --output_dir /root/cogvideox-factory/models/cogvideox-lora__optimizer_adam__steps_3000__lr-schedule_cosine_with_restarts__learning-rate_1e-3/           --max_num_frames 49           --train_batch_size 1           --max_train_steps 3000           --checkpointing_steps 1000           --gradient_accumulation_steps 1           --gradient_checkpointing           --learning_rate 1e-3           --lr_scheduler cosine_with_restarts           --lr_warmup_steps 400           --lr_num_cycles 1           --enable_slicing           --enable_tiling           --optimizer adam           --beta1 0.9           --beta2 0.95           --weight_decay 0.001           --max_grad_norm 1.0           --allow_tf32           --report_to wandb        --nccl_timeout 1800
10/16/2024 00:27:03 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.45s/it]
{'use_learned_positional_embeddings'} was not found in config. Values will be initialized to default values.
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.18.3
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
===== Memory before training =====
memory_allocated=19.906 GB
max_memory_allocated=19.906 GB
max_memory_reserved=20.006 GB
***** Running training *****
  Num trainable parameters = 132120576
  Num examples = 69
  Num epochs = 44
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient accumulation steps = 1
  Total optimization steps = 3000
Steps:   0%|                                                                                                                        | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/cogvideox-factory/training/cogvideox_text_to_video_lora.py", line 924, in <module>
    main(args)
  File "/root/cogvideox-factory/training/cogvideox_text_to_video_lora.py", line 692, in main
    model_output = transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 820, in forward
    return model_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 808, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 464, in forward
    hidden_states, encoder_hidden_states = torch.utils.checkpoint.checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/torch/_compile.py", line 31, in inner
    return disable_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 488, in checkpoint
    ret = function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 459, in custom_forward
    return module(*inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 132, in forward
    attn_hidden_states, attn_encoder_hidden_states = self.attn1(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 491, in forward
    return self.processor(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 1931, in __call__
    query[:, :, text_seq_length:] = apply_rotary_emb(query[:, :, text_seq_length:], image_rotary_emb)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/embeddings.py", line 734, in apply_rotary_emb
    out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 206.00 MiB. GPU 0 has a total capacity of 23.65 GiB of which 41.81 MiB is free. Process 2702404 has 23.60 GiB memory in use. Of the allocated memory 22.07 GiB is allocated by PyTorch, and 1.08 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by a-r-r-o-w** [comment]
Could you make sure to run `training/prepare_dataset.py` before launching training? Once that's done, make sure to use the `--load_tensors` flag so precomputed latents and embeddings can be used. Without precomputing, you will have to load VAE and Text Encoder in memory which will make it go above 24 GB

**Comment by a-r-r-o-w** [comment]
I've pushed some updates to `prepare_dataset.py`. Could you give it a try now?

**Comment by yafangwang9** [comment]
> I've pushed some updates to `prepare_dataset.py`. Could you give it a try now?

Thank you for your reply! However, after running the script, I always encounter a `TypeError: expected Tensor as element 0 in argument 0, but got NoneType`. I checked the size of the `videos` files in the Disney dataset download directory and did not find any abnormalities.


./prepare_dataset.sh 
===== Running `    training/prepare_dataset.py       --model_id THUDM/CogVideoX-5b       --data_root /root/cogvideox-factory/my/datasets       --caption_column /root/cogvideox-factory/my/datasets/prompt.txt       --video_column /root/cogvideox-factory/my/datasets/videos.txt       --output_dir /root/cogvideox-factory/my/datasets/precomputed_data       --height_buckets 480 720       --width_buckets 720 960       --frame_buckets 49       --max_num_frames 49       --max_sequence_length 226       --target_fps 8       --batch_size 1       --dtype fp32
 --save_tensors` =====
Loading checkpoint shards: 100%|████████████████████████| 2/2 [00:05<00:00,  2.50s/it]
Encoding:   0%|                                                | 0/69 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/cogvideox-factory/training/prepare_dataset.py", line 638, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/cogvideox-factory/training/prepare_dataset.py", line 491, in main
    for step, batch in enumerate(iterator):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/root/cogvideox-factory/training/prepare_dataset.py", line 447, in collate_fn
    images = torch.stack(images).to(dtype=weight_dtype, non_blocking=True)
TypeError: expected Tensor as element 0 in argument 0, but got NoneType
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1537, in _shutdown
    atexit_call()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt: 
===== Finished running script =====

**Comment by a-r-r-o-w** [comment]
Oh, sorry, missed another bug! For now, if you pass `--save_image_latents` as well, it should work but we need to make it optional. Will update ASAP

**Comment by a-r-r-o-w** [comment]
Merged #43 which should address this.

- `--save_latents_and_embeddings` for precomputed T2V training.
- Above with `--save_image_latents` for I2V training.

**Comment by yafangwang9** [comment]
> Merged #43 which should address this.
> 
> * `--save_latents_and_embeddings` for precomputed T2V training.
> * Above with `--save_image_latents` for I2V training.

Thank you very much, it worked!😆

**Comment by a-r-r-o-w** [comment]
Awesome! Marking this as resolved then
