### ISSUE TITLE
Computational of num_epoch seems incorrect

### ISSUE THREAD

**Issue by Yuancheng-Xu** [a-r-r-o-w/cogvideox-factory#37]
The current way of computing `args.num_train_epochs` will result in early termination. For example, if we specify 500 steps, the program will actually just run for a lot less steps.

It seems that the issue is [Here](https://github.com/a-r-r-o-w/cogvideox-factory/blob/a6c246c29d11d78e4aa3fb4b137c5ffd8d719d94/training/cogvideox_image_to_video_lora.py#L561) 

```
num_update_steps_per_epoch = math.ceil(len(train_dataset) / args.gradient_accumulation_steps)
args.num_train_epochs = math.ceil(args.max_train_steps / num_update_steps_per_epoch)
```

I think it makes sense to set `num_update_steps_per_epoch=math.ceil(len(train_dataset) / total_batch_size)`, where `total_batch_size = args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps`?

**Comment by sayakpaul** [comment]
Ah, this should have been:

```py
num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
```

That should cut it no?

**Comment by Yuancheng-Xu** [comment]
I believe so yep.

**Comment by sayakpaul** [comment]
Righty! Would you maybe like to open a PR for it?

**Comment by Yuancheng-Xu** [comment]
Wait I think the following two are different. In the case where we have 500 examples, 8Gpus, device_batch_size =2 and grad_accumulation_steps=1
```
total_batch_size = args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps
num_update_steps_per_epoch=math.ceil(len(train_dataset) / total_batch_size)
```
will compute num_update_steps_per_epoch = 500 / (8 * 2 * 1)

and 
```
num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
```
will compute  num_update_steps_per_epoch = (500/2) / 1.

Which one is it?

**Comment by sayakpaul** [comment]
I _think_ it should be the latter.

**Comment by Yuancheng-Xu** [comment]
When I try to access `len(train_dataloader)` I encounter this error. Wondering how to fix it?

```
[rank1]:   File "/root/anaconda3/envs/cogvideox-i2v/lib/python3.11/site-packages/accelerate/data_loader.py", line 445, in __len__                                                                      
[rank1]:     return len(self.base_dataloader)                                                                                                                                                          
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/anaconda3/envs/cogvideox-i2v/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 485, in __len__                                                                 
[rank1]:     return len(self._index_sampler)                                                                                                                                                           
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                           
[rank1]:   File "/root/anaconda3/envs/cogvideox-i2v/lib/python3.11/site-packages/accelerate/data_loader.py", line 170, in __len__                                                                      
[rank1]:     if len(self.batch_sampler) % self.num_processes == 0:                                                                                                                                     
[rank1]:        ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                
[rank1]:   File "/root/anaconda3/envs/cogvideox-i2v/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 306, in __len__                                                                    
[rank1]:     return (len(self.sampler) + self.batch_size - 1) // self.batch_size  # type: ignore[arg-type]                                                                                             
[rank1]:             ^^^^^^^^^^^^^^^^^                                                                                                                                                                 
[rank1]: TypeError: object of type 'BucketSampler' has no len()   
```

**Comment by a-r-r-o-w** [comment]
This is because `__len__` is not implemented on `BucketSampler` and it might actually be quite difficult to know the length of dataloader beforehand. Each bucket in the sampler must have `train_batch_size` number of entries before it is dispatched. Depending on `drop_last`, partially full buckets may be dispatched too. We don't have the height/width information beforehand with decord and must load all videos in memory, to get their height/width/num_frames, if we'd like to calculate number of batches that will be dispatched. This will basically make it infeasible with large video datasets unless extra metadata is stored that allow us to retrieve this info without loading videos into memory. OpenCV allows this, by loading just the first standing frame, but with decord VideoReader, the entire video is loaded into memory.

I think the best thing to do is add extra metadata in `prepare_dataset.py`, which will allow us to then calculate length of dataloader efficiently.

**Comment by Yuancheng-Xu** [comment]
I see.

I tried the first implementation though
```
total_batch_size = args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps
num_update_steps_per_epoch=math.ceil(len(train_dataset) / total_batch_size)
```

and I noticed that the process ends correctly according to the tqdm bar: If I set args.max_train_steps to be 1000, then the program correctly ends at step=1000; Does this mean that this is the correct implementation though?

**Comment by a-r-r-o-w** [comment]
I think it will be correct if drop_last=False for the bucket sampler. For drop_last=True, not sure :/

**Comment by a-r-r-o-w** [comment]
@Yuancheng-Xu let me know if we can close this. I believe it should be fixed for the moment (assuming everyone is using drop_last=False as default). For the other case, we can revisit later

**Comment by Yuancheng-Xu** [comment]
Yep I am closing the issue. Thanks!
