### ISSUE TITLE
Support multi-resolution/frame bucketing in `prepare_dataset.py` and multi-GPU

### ISSUE THREAD

**Issue by a-r-r-o-w** [a-r-r-o-w/cogvideox-factory#4]

**Comment by sayakpaul** [comment]
What are we missing here? A good reference here is https://github.com/PixArt-alpha/PixArt-alpha/ (it implements aspect ratio bucketing).

**Comment by a-r-r-o-w** [comment]
I've rewritten the prepare dataset script but some parts are still remaining. Will push by EOD
