### ISSUE TITLE
How to load the fine-tuned I2V model's LoRA module

### ISSUE THREAD

**Issue by Yuancheng-Xu** [a-r-r-o-w/cogvideox-factory#40]
I have successfully fine-tuned an I2V model (locally, without pushing to HF) and would like to load it for inference. I use the following code suggested in the readme

```
model_name = "THUDM/CogVideoX-5b-I2V" 
pipe = CogVideoXImageToVideoPipeline.from_pretrained(
    model_name, torch_dtype=torch.bfloat16
).to("cuda")

pipe.load_lora_weights("MyLocalLoRAPath", adapter_name=["cogvideox-lora"])
pipe.set_adapters(["cogvideox-lora"], [1.0])
```

However I encounter the error 

```
File ~/anaconda3/envs/cogvideox-i2v/lib/python3.11/site-packages/diffusers/loaders/lora_pipeline.py:2451, in CogVideoXLoraLoaderMixin.load_lora_into_transformer(cls, state_dict, transformer, adapter_name, _pipeline):

if adapter_name in getattr(transformer, "peft_config", {}):
aise ValueError(
   f"Adapter name {adapter_name} already in use in the transformer - please select a new adapter name."    )

TypeError: unhashable type: 'list'
```

Note: in the trained LoRA folders, there is only a `pytorch_lora_weights.safetensors`

**Comment by a-r-r-o-w** [comment]
In pipe.load_lora_weights, please pass just the string for adapter_name and not a list

**Comment by euminds** [comment]
> I have successfully fine-tuned an I2V model (locally, without pushing to HF) and would like to load it for inference. I use the following code suggested in the readme
> 
> ```
> model_name = "THUDM/CogVideoX-5b-I2V" 
> pipe = CogVideoXImageToVideoPipeline.from_pretrained(
>     model_name, torch_dtype=torch.bfloat16
> ).to("cuda")
> 
> pipe.load_lora_weights("MyLocalLoRAPath", adapter_name=["cogvideox-lora"])
> pipe.set_adapters(["cogvideox-lora"], [1.0])
> ```
> 
> However I encounter the error
> 
> ```
> File ~/anaconda3/envs/cogvideox-i2v/lib/python3.11/site-packages/diffusers/loaders/lora_pipeline.py:2451, in CogVideoXLoraLoaderMixin.load_lora_into_transformer(cls, state_dict, transformer, adapter_name, _pipeline):
> 
> if adapter_name in getattr(transformer, "peft_config", {}):
> aise ValueError(
>    f"Adapter name {adapter_name} already in use in the transformer - please select a new adapter name."    )
> 
> TypeError: unhashable type: 'list'
> ```
> 
> Note: in the trained LoRA folders, there is only a `pytorch_lora_weights.safetensors`


Is your device a 4090 24GB or H100 or A100?
