### ISSUE TITLE
request for gradio UI , dataset captioning scripts 

### ISSUE THREAD

**Issue by GeeveGeorge** [a-r-r-o-w/cogvideox-factory#44]
### Feature request  / 功能建议

@a-r-r-o-w @sayakpaul 

it would be great if a gradio UI could be made for fine-tuning CogVideoX.
Users can provide path to videos (no need to upload) , just a path.
Then hit fine-tune lora (it needs to split videos, caption it (say using BLIP), and prepare the dataset for fine-tuning.
Then run fine-tuning on single GPU and get the lora. 
Users can also test inference on a different gradio UI by specifying the lora path.

It would be great if you could take this into consideration to make it super user friendly. 

I could help as well making the gradio UI, if the data prep and captioning scripts are available.

### Motivation / 动机

better UX UI for new comers.

### Your contribution / 您的贡献

gradio UI

**Comment by sayakpaul** [comment]
The repository is supposed to be hackable so, a UI is currently not on our priority. Feel free work on separately and we will try to help. Regarding captioning, see https://github.com/a-r-r-o-w/cogvideox-factory/pull/34/.

**Comment by GeeveGeorge** [comment]
@sayakpaul what about a data prep script tho (given a path, it splits into proper chunks and also captions the videos using say BLIP 2) , can we expect that script @a-r-r-o-w

**Comment by sayakpaul** [comment]
With the existing scripts, it should not be too hard. Feel free to start one if you want. Multi-frame, multi-aspect sampling are already supported. Please read dataset.md doc.

**Comment by a-r-r-o-w** [comment]
I think it might be interesting and make things easier to work with, considering that all users may not be researchers. I did get a few DMs requesting a UI too, as the different configurations can be hard to understand.

@GeeveGeorge As Sayak mentioned, we are short on time so cannot prioritize, but if you could create a prototype and open a PR, we would be more than happy to help assist. Thanks!
