### ISSUE TITLE
AttributeError: 'CogVideoXTransformer3DModel' object has no attribute 'add_adapter'

### ISSUE THREAD

**Issue by YLongJin** [a-r-r-o-w/cogvideox-factory#46]
### System Info / 系統信息

diffusers                0.30.3

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 975, in <module>
[rank0]:     main(args)
[rank0]:   File "/mnt/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 411, in main
[rank0]:     transformer.add_adapter(transformer_lora_config)
[rank0]:   File "/opt/conda/envs/flux/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 151, in __getattr__
[rank0]:     return super().__getattr__(name)
[rank0]:   File "/opt/conda/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
[rank0]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank0]: AttributeError: 'CogVideoXTransformer3DModel' object has no attribute 'add_adapter'

### Expected behavior / 期待表现

when I "bash train_image_to_video_lora.sh" I got this bug, I use the requirement depends!

**Comment by YLongJin** [comment]
I fix it use
git clone https://github.com/huggingface/diffusers
cd diffusers
pip install .

but I got

RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[13, 32, 60, 90] to have 16 channels, but got 32 channels instead

could you help me to run it

**Comment by MustafaUtkuAydogdu** [comment]
Same error here. I got it when I run the train_text_to_video_lora.sh

**Comment by a-r-r-o-w** [comment]
Is it the `add_adapter` error? If yes, you will need to install diffusers from the main branch.

If it's the channels runtime error, can you share your launch script? Need to make sure we're using the same thing as I'm unable to reproduce it

**Comment by Yuancheng-Xu** [comment]
Installing from source `pip install git+https://github.com/huggingface/diffusers` can solve this.

**Comment by sayakpaul** [comment]
Thanks @Yuancheng-Xu! Do you maybe want to drop a PR to add a note about this?

**Comment by Yuancheng-Xu** [comment]
Yep just did!

**Comment by a-r-r-o-w** [comment]
@Yuancheng-Xu Could you open a PR from your branch 😅

**Comment by Yuancheng-Xu** [comment]
Oops my bad. Just did

**Comment by YLongJin** [comment]
@a-r-r-o-w 
<<<<<<< Updated upstream
OUTPUT_DIR="/path/to/my/datasets/preprocessed-dataset"
HEIGHT_BUCKETS="480 720"
WIDTH_BUCKETS="720 960"
FRAME_BUCKETS="49"
MAX_NUM_FRAMES="49"
=======
OUTPUT_DIR="/mnt/cogvideox-factory/Disney-VideoGeneration-Dataset/preprocessed-dataset"
HEIGHT=480
WIDTH=720
MAX_NUM_FRAMES=49
>>>>>>> Stashed changes
MAX_SEQUENCE_LENGTH=226
TARGET_FPS=8
BATCH_SIZE=1
DTYPE=fp32

# To create a folder-style dataset structure without pre-encoding videos and captions
# For Image-to-Video finetuning, make sure to pass `--save_image_latents`
CMD_WITHOUT_PRE_ENCODING="\
  torchrun --nproc_per_node=$NUM_GPUS \
    training/prepare_dataset.py \
      --model_id $MODEL_ID \
      --data_root $DATA_ROOT \
      --caption_column $CAPTION_COLUMN \
      --video_column $VIDEO_COLUMN \
      --output_dir $OUTPUT_DIR \
      --height_buckets $HEIGHT_BUCKETS \
      --width_buckets $WIDTH_BUCKETS \
      --frame_buckets $FRAME_BUCKETS \
      --max_num_frames $MAX_NUM_FRAMES \
      --max_sequence_length $MAX_SEQUENCE_LENGTH \
      --target_fps $TARGET_FPS \
      --batch_size $BATCH_SIZE \
      --dtype $DTYPE \
      --save_image_latents \
"

CMD_WITH_PRE_ENCODING="$CMD_WITHOUT_PRE_ENCODING --save_latents_and_embeddings"

# Select which you'd like to run
CMD=$CMD_WITH_PRE_ENCODING




Then I run  train_image_to_video_lora.sh


I got RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[13, 32, 60, 90] to have 16 channels, but got 32 channels instead

**Comment by YLongJin** [comment]
@a-r-r-o-w 
export TORCH_LOGS="+dynamo,recompiles,graph_breaks"
export TORCHDYNAMO_VERBOSE=1
export WANDB_MODE="offline"
export NCCL_P2P_DISABLE=1
export TORCH_NCCL_ENABLE_MONITORING=0

GPU_IDS="1"

# Training Configurations
# Experiment with as many hyperparameters as you want!
LEARNING_RATES=("1e-4" "1e-3")
LR_SCHEDULES=("cosine_with_restarts")
OPTIMIZERS=("adamw")
MAX_TRAIN_STEPS=("3000")

# Single GPU uncompiled training
ACCELERATE_CONFIG_FILE="/mnt/cogvideox-factory/onegup_default_config.yaml"

# Absolute path to where the data is located. Make sure to have read the README for how to prepare data.
# This example assumes you downloaded an already prepared dataset from HF CLI as follows:
#   huggingface-cli download --repo-type dataset Wild-Heart/Disney-VideoGeneration-Dataset --local-dir /path/to/my/datasets/disney-dataset
DATA_ROOT="/mnt/cogvideox-factory/Disney-VideoGeneration-Dataset/preprocessed-dataset"
CAPTION_COLUMN="/mnt/cogvideox-factory/Disney-VideoGeneration-Dataset/preprocessed-dataset/prompt.txt"
VIDEO_COLUMN="/mnt/cogvideox-factory/Disney-VideoGeneration-Dataset/preprocessed-dataset/videos.txt"

# Launch experiments with different hyperparameters
for learning_rate in "${LEARNING_RATES[@]}"; do
  for lr_schedule in "${LR_SCHEDULES[@]}"; do
    for optimizer in "${OPTIMIZERS[@]}"; do
      for steps in "${MAX_TRAIN_STEPS[@]}"; do
        output_dir="/path/to/my/models/cogvideox-lora__optimizer_${optimizer}__steps_${steps}__lr-schedule_${lr_schedule}__learning-rate_${learning_rate}/"

        cmd="accelerate launch --config_file $ACCELERATE_CONFIG_FILE --gpu_ids $GPU_IDS training/cogvideox_image_to_video_lora.py \
          --pretrained_model_name_or_path CogVideoX-5b \
          --data_root $DATA_ROOT \
          --caption_column $CAPTION_COLUMN \
          --video_column $VIDEO_COLUMN \
          --id_token BW_STYLE \
          --height_buckets 480 \
          --width_buckets 720 \
          --frame_buckets 49 \
          --dataloader_num_workers 8 \
          --pin_memory \
          --validation_prompt \"a girl happy\" \
          --validation_images \"/mnt/anime/sensitive/danbooru_989914_f4a555b1d9572b0cf8d6731b87cf0ca8.jpg\" \
          --validation_prompt_separator ::: \
          --num_validation_videos 1 \
          --validation_epochs 100 \
          --seed 42 \
          --rank 128 \
          --lora_alpha 128 \
          --mixed_precision bf16 \
          --output_dir $output_dir \
          --max_num_frames 49 \
          --train_batch_size 1 \
          --max_train_steps $steps \
          --checkpointing_steps 1000 \
          --gradient_accumulation_steps 1 \
          --gradient_checkpointing \
          --learning_rate $learning_rate \
          --lr_scheduler $lr_schedule \
          --lr_warmup_steps 400 \
          --lr_num_cycles 1 \
          --enable_slicing \
          --enable_tiling \
          --noised_image_dropout 0.05 \
          --optimizer $optimizer \
          --beta1 0.9 \
          --beta2 0.95 \
          --weight_decay 0.001 \
          --max_grad_norm 1.0 \
          --allow_tf32 \
          --report_to wandb \
          --nccl_timeout 1800 \
          --load_tensors
        "
        
        echo "Running command: $cmd"
        eval $cmd
        echo -ne "-------------------- Finished executing script --------------------\n\n"
      done
    done
  done
done

**Comment by sayakpaul** [comment]
I think this is already solved?
