### ISSUE TITLE
New prepare dataset = instant oom even on one video

### ISSUE THREAD

**Issue by Cubey42** [a-r-r-o-w/cogvideox-factory#47]
I have run prepare_dataset.py in the past but since the rework I can't get past encoding videos, it takes up my 24gb 4090 and my 64gb of RAM

**Comment by a-r-r-o-w** [comment]
Could you share the exact command you are running with? Will try to repro on 24gb 4090 as well. It's important to make sure `--enable_tiling`, and `--enable_slicing` (if batch_size is > 1, otherwise the intermediate states in VAE can take close to 20 GB by themselves apart from model weights).

**Comment by Cubey42** [comment]
I did not prepare with tiling or slicing, I just used my old command, I'll try again today

**Comment by Cubey42** [comment]
It was my lack of --use_tiling, thank you.
