### ISSUE TITLE
Can I change frame_buckets parameter In case of LORA training?

### ISSUE THREAD

**Issue by FDoKE** [a-r-r-o-w/cogvideox-factory#56]
Can I change frame_buckets parameter in case of LORA training? (if I want to train on 16 frames videos)
Or it should be 49 as the base model? (in my case THUDM/CogVideoX-5b-I2V)

**Comment by a-r-r-o-w** [comment]
Yes, you should be able to change the number of frames. However, keep in mind that the VAE implementation is only compatible with `4 * k` or `4 * k + 1` number of frames, and the first frame will be taken as condition for I2V.
