### ISSUE TITLE
Is portrait resolution supported?

### ISSUE THREAD

**Issue by jinqiupeter** [a-r-r-o-w/cogvideox-factory#64]
### System Info / 系統信息

It'd be great to train with portrait(竖屏) videos

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

N/A

### Expected behavior / 期待表现

Able to train with portrait videos

**Comment by sayakpaul** [comment]
Provide more details in English so that all the maintainers of this repository could take part in the discussions.

**Comment by jinqiupeter** [comment]
I was asking if cogvideo-factory can train portrait resolutions such as (1280 height, 720 width).

**Comment by a-r-r-o-w** [comment]
Yes, after #31, you should be able to train at any resolution for I2V models. T2V multiresolution training is already supported - you need to specify `--height_buckets`, `--width_buckets` and `--frame_buckets`. You can set these to your custom portrait resolutions. Will try and make it more convenient soon

**Comment by jinqiupeter** [comment]
Thank you! Looking forward to #31 to be merged.

**Comment by a-r-r-o-w** [comment]
Thanks for patiently waiting! It has been merged now. Feel free to try it out and let me know if you encounter any problems
