### ISSUE TITLE
TARGET_FPS variable in prepare_dataset.sh

### ISSUE THREAD

**Issue by MustafaUtkuAydogdu** [a-r-r-o-w/cogvideox-factory#69]
I am confused about the purpose of the TARGET_FPS variable in prepare_dataset.sh. I have videos consisting of 128 frames. What is the effect of TARGET_FPS = 8 in this case?

**Comment by a-r-r-o-w** [comment]
TARGET_FPS does nothing but save output pre-processed videos at a specific FPS. It does not have anything to do with training. So, if you choose frame buckets as say `48` and `88`, your preprocessed videos will be saved with lengths 6 seconds and 11 seconds. Even if it is not a perfect multiple, it will not affect the number of frames you are using for training so you can safely ignore it
