### ISSUE TITLE
For whom has problem when inferencing

### ISSUE THREAD

**Issue by HWT-WalterHu** [a-r-r-o-w/cogvideox-factory#71]
### System Info / 系統信息

Diffusers = 0.31

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

from diffusers import export_to_video

should be 
from diffusers.utils import export_to_video

### Expected behavior / 期待表现

Error info: cannot import name 'export_to_video' from 'diffusers'

**Comment by a-r-r-o-w** [comment]
Thanks. Which file are you referring to that contains this error?

**Comment by HWT-WalterHu** [comment]
> Thanks. Which file are you referring to that contains this error?

The codes are from the inference example in main-page of the project(REAMDE.md),  section of quickstart.

**Comment by a-r-r-o-w** [comment]
Oh I see, thanks - will fix asap!
