### ISSUE TITLE
way to reduce memory cost

### ISSUE THREAD

**Issue by WangFeng18** [a-r-r-o-w/cogvideox-factory#72]
Hi, thanks for the project. I wonder why the current scripts can save a lot of gpu memory costs compared to cogvideo repo. Another question is that I found inference cost more gpu(npu in my environment) memory than training, and I encountered oom in npu environment（with 64GB npu memory）, could you please give me some hints for reasons of this phenomenon (inference cost more memory than training). 
Thank you!

**Comment by sayakpaul** [comment]
> Hi, thanks for the project. I wonder why the current scripts can save a lot of gpu memory costs compared to cogvideo repo.

The memory savings primarily come from precomputation of latents and text embeddings. 

> Another question is that I found inference cost more gpu(npu in my environment) memory than training, and I encountered oom in npu environment（with 64GB npu memory）, could you please give me some hints for reasons of this phenomenon (inference cost more memory than training).

We don't have access to an NPU device so, we're unable to offer help regarding that at the moment.
